### ISSUE TITLE
Multiple query symbol

### ISSUE THREAD

**Issue by yingwei1025** [ricardo93borges/alphavantage-wrapper-ts#19]
Hi thanks for creating this, can it query multiple symbol in one time?
```
symbols= ["IBM", "MSFT", "APPL"]
```
```
av.fundamentalData
  .companyOverview({ symbol: 'IBM' })
  .then((data) => console.log(data));
```

**Comment by ricardo93borges** [comment]
Hi, this is not supported yet, that would require multiple requests to the Alphavantage API (https://www.alphavantage.co/documentation/#company-overview)
