### ISSUE TITLE
[feature] Custom request method

### ISSUE THREAD

**Issue by dawadam** [ricardo93borges/alphavantage-wrapper-ts#32]
Hi,
Great job always, thanks.
Is it possible to add custom request method ?

To make request of a non-existing implementation.

Like this : 

```
const functionName = 'LISTING_STATUS'
const params = {
    date: '2013-08-03'
}
const response = await av.customRequest(functionName, params)
```

**Comment by ricardo93borges** [comment]
Hi, it is, but the essential purpose of this package is to have the types of what the API returns, so if this feature is implemented it has to ensure that all the possible results of the API are typed, which will be accomplished eventually by implementing the functions one by one.
